# Generated by Django 4.1.3 on 2022-11-11 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='nome',
            new_name='login',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='data_nascimento',
            field=models.CharField(max_length=30),
        ),
    ]
