# Generated by Django 4.1.3 on 2022-11-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_nome_cliente_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='login',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='senha',
            field=models.CharField(max_length=15),
        ),
    ]
